module.exports={   
  //collections 
  USER_COLLECTION:'USERS', 
  PRODUCT_COLLECTION:'PRODUCTS',
  CATEGORY_COLLECTION:'CATEGORIES' ,
  CART_COLLECTION:'CART' ,
  ORDER_COLLECTION:'ORDERS',
  WISHLIST_COLLECTION:'WISHLIST',   
  COUPON_COLLECTION:'COUPONS',
  BANNER_COLLECTION:'BANNERS'
}